### ISSUE TITLE
By default, free asset dispensing is not open to all

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#1723]
### Background
I found this when publishing the CEXA price feed. (Published [here](https://market.oceanprotocol.com/asset/did:op:0dac5eb4965fb2b485181671adbf3a23b0133abf71d2775eda8043e8efc92d19)).

This meant that, in the [README](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/predict-eth.md) that uses the price feed, no one was allowed to come along and request tokens from the dispenser.

### Core problem

The problem was that by default, in the dispenser contract, it sets [`allowedSwapper`](https://github.com/oceanprotocol/contracts/blob/722f6cb91ec2a3c5966b919888b2633601e6ecab/contracts/pools/dispenser/Dispenser.sol#L25) to nonzero address (not 0x00...). Which meant that *only* the publishing account can dispense tokens, unless it's changed via [`setAllowedSwapper()`](https://github.com/oceanprotocol/contracts/blob/722f6cb91ec2a3c5966b919888b2633601e6ecab/contracts/pools/dispenser/Dispenser.sol#L205).

I looked around in Ocean Market to try to change it, such that I could allow anyone to request tokens. Eg next to "change ddo". Such an option did not exist.

But I did find a workaround, in code: via Python, I updated the allowedSwapper to zero address (0x00..) manually. In that setting, it means that anyone can request tokens ([ref](https://github.com/oceanprotocol/contracts/blob/722f6cb91ec2a3c5966b919888b2633601e6ecab/contracts/pools/dispenser/Dispenser.sol#L238)).

### Candidate solutions

What to do for Ocean Market? I see four design options A, B, C, D.

**Option A.** Market could offers two choices:
  1. anyone can request 
  2. only pre-set address can request. If this: can set the address within Ocean Market 
 
**Option B.** Only offer choice (1) - anyone can request

**Option C.** Only offer choice (2) - only pre-set address can request, without an affordance to set address. (This is the status quo.)

**Option D.** Only offer choice (2) - only pre-set address can request, _with_ some affordance to set the address.

#### Analysis:
- any flow with (2) adds complexity, because it implies that someone is managing access and doling out tokens. This is options A, C, or D.
- whereas if we do just (1) - option B where anyone can request - it's simple and non-constraining. Making this change in Ocean Market is likely just changing one line of code: wherever it calls [`dispenser.create()`](https://github.com/oceanprotocol/contracts/blob/722f6cb91ec2a3c5966b919888b2633601e6ecab/contracts/pools/dispenser/Dispenser.sol#L154), set the parameter allowedSwapper to 0x00...

**I recommend that we do just (1) - option B where anyone can request. Simple change, keep UX simple, move on.**

**Comment by kremalicious** [comment]
> wherever it calls [dispenser.create()](https://github.com/oceanprotocol/contracts/blob/722f6cb91ec2a3c5966b919888b2633601e6ecab/contracts/pools/dispenser/Dispenser.sol#L154), set the parameter allowedSwapper to 0x00...

that's exactly what we do:
https://github.com/oceanprotocol/market/blob/c8b8db9b52729cd4c137f651561cf15d1af3f6aa/src/components/Publish/_utils.ts#L266

I can successfully download any other free asset on the market, like [this one](https://market.oceanprotocol.com/asset/did:op:ab8ff79c8b48757cbeeb5100758d8d34fa5709ad6caca5d2308b346315119d47).

If you publish outside of market UI we can't control what parameters you set when publishing.

**Comment by trentmc** [comment]
Actually, I published the asset inside the market UI.

Re-opening

**Comment by trentmc** [comment]
Here's how you can reproduce:

1. Publish any asset via Market UI. Note its did.
2. Try to request dispense from ocean.js or ocean.py, from an address different than the one you published with. It will fail

**Comment by kremalicious** [comment]
Still not reproducible, no other free asset has this problem. No newly published free asset has this problem. Published multiple free assets (like [this one](https://market.oceanprotocol.com/asset/did:op:48053842ec34ffd69f9ce2b32f8c9c93cf6b73465dad5cead163e1535ccf75f7)), can download them all with another account. Non-reproducible issue should be closed.

**Comment by trentmc** [comment]
Try reproducing by
1. Publish any asset via Market UI. Note its did.
2. Do steps 1 & 2 of [this flow](https://github.com/oceanprotocol/ocean.py/blob/164a60cc1c94ef839b55f71ec05d9e84f743ff39/READMEs/predict-eth.md), replacing the did with the previous step's did

**Comment by kremalicious** [comment]
So dispensing vs. ordering. By design only the publisher is allowed to dispense datatokens as otherwise everybody can drain the dispenser of all available tokens. Everybody else needs to go through order flow, which in market we do with ocean.js which calls `buyFromDispenserAndOrder()` on the datatoken contract, like here for [mentioned new asset](https://market.oceanprotocol.com/asset/did:op:48053842ec34ffd69f9ce2b32f8c9c93cf6b73465dad5cead163e1535ccf75f7): https://mumbai.polygonscan.com/tx/0x26ca081cb956bf794324340cdb0482a5fe4ef10dc384801a0d8f0d3d0172f590

So not sure if this design should be changed.

As for `allowedSwapper`, I indeed find a lot of weird things. My [asset creation tx](https://mumbai.polygonscan.com/tx/0x30229b7021444f2594513610918ffb96ab45b98308d65f17b462d970db6cd8be) in the end sets `allowedSwapper` to the datatoken address despite market sending a zero address along the stack. So I would expect `allowedSwapper` to always be the zero address when publishing from market.

**Comment by trentmc** [comment]
> So I would expect allowedSwapper to always be the zero address when publishing from market, but this seems to be a problem somewhere further down the stack.

Interesting that you got the error too. "It was _supposed_ to work, but it doesn't"

FYI in my original problem, I'd queried the `allowedSwapper` address; and it was not 0x00.

**Comment by kremalicious** [comment]
Think I'm back again at isolating it to market. Over in ocean.js added [specific tests for this](https://github.com/oceanprotocol/ocean.js/pull/1632/files) and there the event emitted always has `allowedSwapper` as the zero address, run against barge:

<img width="638" alt="Screen Shot 2022-10-04 at 15 44 32" src="https://user-images.githubusercontent.com/90316/193850429-8575a5a6-5f55-4fe7-aa07-5a069dc743f7.png">

When calling same method with same params from market, run against Mumbai, I instead get datatoken address returned as `allowedSwapper`, so it stays mysterious:

<img width="574" alt="Screen Shot 2022-10-04 at 15 40 06" src="https://user-images.githubusercontent.com/90316/193849325-a2260874-1249-4859-b81b-fd5fc56d3379.png">

So either something gets lost in market when passing params or something is different with the deployed remote contracts, but for both things I just can't find anything yet

**Comment by kremalicious** [comment]
More fun findings: when using `createNftWithDatatokenWithDispenser()` from market, an additional `DispenserAllowedSwapperChanged` event is emitted, which is not emitted when run in ocean.js tests. And this event then shows the datatoken address has been set.

**Comment by mihaisc** [comment]
It seems an issue in the contract. Check [this tx ](https://goerli.etherscan.io/tx/0x889bc4e15e1da8381a07d1cebc4d3070fc2f4a5fad0d776d393ad9e7c4fa439d#eventlog). The input data is ok `_DispenserData.allowedSwapper	address	0x0000000000000000000000000000000000000000`
But in the events :

![image](https://user-images.githubusercontent.com/26000280/194007466-cd7a4312-366c-41dd-8c16-e2157fe3b97a.png)

**Comment by mihaisc** [comment]
Okk..i went down the rabbit hole and got confused as well :) . The market works fine, i can download the assets published by @kremalicious . If you are using the enterprise template (we are using it in our market ) you need to call datatoken.buyFromFreAndOrder  (in contracts it's `buyFromDispenserAndOrder` ).
In the readme you are trying to buy a datatoken and then order, this will work for the simple datatoken template.

So instead of this: 

```
ocean.dispenser.dispense_tokens(datatoken, amt_dispense_wei, consumer_wallet=alice_wallet)
bal = ocean.from_wei(datatoken.balanceOf(alice_wallet.address))
print(f"Alice now holds {bal} datatokens to access the data asset.")

# Alice sends datatoken to the service, to get access
order_tx_id = ocean.assets.pay_for_access_service(asset, alice_wallet)
print(f"order_tx_id = '{order_tx_id}'")
```
you just neet to call  `buyFromDispenserAndOrder`

**Comment by trentmc** [comment]
Thanks @mihaMI a and @kremaliciou for the digging.

I will update the ocean.py READMEs accordingly.

And for that, I will take this ticket, and transfer it to ocean.py repo.
